name: delivaryhalaapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  location: ^5.0.0
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  latlong2: ^0.8.1
  flutter_map: ^3.1.0
  http: ^0.13.6
  flutter_compass: ^0.8.0
  sensors_plus: ^3.0.3
  url_launcher: ^6.0.0
  maps_launcher: ^2.2.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  flutter_map_marker_cluster: ^1.1.0
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  gradient_slide_to_act: ^0.0.2
  firebase_messaging: ^14.6.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/Img/
    - assets/shape/
    - assets/lotte/

